[package]
name = "bt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true

[profile.release.build-override]
opt-level = 3
codegen-units = 1